---
- hosts: 172.31.89.78
  become: yes
  tasks:
  - include: myFile.yml
  - name: install webserver on ubuntu
    apt:
     name: apache2
     state: present
  - name: i want to index file into node server
    copy:
      src: myIndexpage
      dest:  /var/www/html/index.html
    notify: restartwebserver
  - name: copy dyno files into nodes
    template:
      src: myDynoindex.j2
      dest: /var/www/html/index.html 
    notify: restartwebserver
  - name: download file
    get_url:
     url: https://sg.mirror.servanamanaged.com/jenkins/windows-stable/2.387.3/jenkins.msi
     dest: /ome/ubuntu/jenkin.msi
     force_basic_auth : yes

  handlers:
  - name: restartwebserver 
    service: 
      name: apache2
      state: restarted
